# Generated by Codex on 2026-03-21

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="RealEstateFund",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("run_id", models.UUIDField(db_index=True, default=uuid.uuid4)),
                ("source", models.CharField(max_length=120)),
                ("url", models.URLField(max_length=500)),
                ("collected_at_utc", models.DateTimeField(db_index=True)),
                ("ticker", models.CharField(db_index=True, max_length=20)),
                ("segment", models.CharField(blank=True, max_length=120, null=True)),
                ("price", models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ("ffo_yield", models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ("dividend_yield", models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ("price_to_book", models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ("market_value", models.DecimalField(blank=True, decimal_places=2, max_digits=24, null=True)),
                ("liquidity", models.DecimalField(blank=True, decimal_places=2, max_digits=24, null=True)),
                ("property_count", models.PositiveIntegerField(blank=True, null=True)),
                ("price_per_sqm", models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ("rent_per_sqm", models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ("cap_rate", models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ("avg_vacancy", models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "real_estate_fund",
                "indexes": [models.Index(fields=["ticker", "collected_at_utc"], name="idx_ref_ticker_collected")],
                "constraints": [
                    models.UniqueConstraint(fields=("run_id", "ticker"), name="uq_real_estate_fund_run_id_ticker")
                ],
            },
        ),
        migrations.CreateModel(
            name="RealEstateFundDetail",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("run_id", models.UUIDField(db_index=True)),
                ("source", models.CharField(max_length=120)),
                ("url", models.URLField(max_length=500)),
                ("detail_url", models.URLField(blank=True, max_length=500, null=True)),
                ("collected_at_utc", models.DateTimeField(db_index=True)),
                ("collection_status", models.CharField(blank=True, max_length=32, null=True)),
                ("identification_name", models.TextField(blank=True, null=True)),
                ("identification_segment", models.CharField(blank=True, max_length=120, null=True)),
                ("identification_mandate", models.CharField(blank=True, max_length=120, null=True)),
                ("identification_management", models.CharField(blank=True, max_length=120, null=True)),
                ("market_price", models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ("market_last_quote_date", models.CharField(blank=True, max_length=32, null=True)),
                ("market_low_52w", models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ("market_high_52w", models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ("market_avg_volume_2m", models.DecimalField(blank=True, decimal_places=2, max_digits=24, null=True)),
                ("market_market_value", models.DecimalField(blank=True, decimal_places=2, max_digits=24, null=True)),
                ("market_share_count", models.DecimalField(blank=True, decimal_places=2, max_digits=24, null=True)),
                ("market_report_date", models.CharField(blank=True, max_length=32, null=True)),
                ("market_last_quarter_info_date", models.CharField(blank=True, max_length=32, null=True)),
                ("oscillations", models.JSONField(blank=True, null=True)),
                ("indicators_ffo_yield", models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ("indicators_ffo_per_share", models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ("indicators_dividend_yield", models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ("indicators_dividend_per_share", models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ("indicators_price_to_book", models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ("indicators_book_value_per_share", models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ("results_last_12m_revenue", models.DecimalField(blank=True, decimal_places=2, max_digits=24, null=True)),
                ("results_last_3m_revenue", models.DecimalField(blank=True, decimal_places=2, max_digits=24, null=True)),
                ("results_last_12m_asset_sales", models.DecimalField(blank=True, decimal_places=2, max_digits=24, null=True)),
                ("results_last_3m_asset_sales", models.DecimalField(blank=True, decimal_places=2, max_digits=24, null=True)),
                ("results_last_12m_ffo", models.DecimalField(blank=True, decimal_places=2, max_digits=24, null=True)),
                ("results_last_3m_ffo", models.DecimalField(blank=True, decimal_places=2, max_digits=24, null=True)),
                ("results_last_12m_distributed_income", models.DecimalField(blank=True, decimal_places=2, max_digits=24, null=True)),
                ("results_last_3m_distributed_income", models.DecimalField(blank=True, decimal_places=2, max_digits=24, null=True)),
                ("balance_sheet_assets", models.DecimalField(blank=True, decimal_places=2, max_digits=24, null=True)),
                ("balance_sheet_net_equity", models.DecimalField(blank=True, decimal_places=2, max_digits=24, null=True)),
                ("properties_property_count", models.PositiveIntegerField(blank=True, null=True)),
                ("properties_unit_count", models.PositiveIntegerField(blank=True, null=True)),
                ("properties_area_sqm", models.DecimalField(blank=True, decimal_places=4, max_digits=24, null=True)),
                ("properties_price_per_sqm", models.DecimalField(blank=True, decimal_places=4, max_digits=24, null=True)),
                ("properties_rent_per_sqm", models.DecimalField(blank=True, decimal_places=4, max_digits=24, null=True)),
                ("properties_cap_rate", models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ("properties_avg_vacancy", models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ("properties_to_equity_percent", models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "fund",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="detail",
                        to="api.realestatefund",
                    ),
                ),
            ],
            options={
                "db_table": "real_estate_fund_detail",
                "indexes": [models.Index(fields=["run_id", "collection_status"], name="idx_ref_detail_run_status")],
            },
        ),
    ]
