# Generated by Django 5.2.12 on 2026-03-21 02:20

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RealEstateFund',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_id', models.UUIDField(db_index=True, default=uuid.uuid4)),
                ('source', models.CharField(max_length=120)),
                ('url', models.URLField(max_length=500)),
                ('collected_at_utc', models.DateTimeField(db_index=True)),
                ('papel', models.CharField(db_index=True, max_length=20)),
                ('segmento', models.CharField(blank=True, max_length=120, null=True)),
                ('cotacao', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ('ffo_yield', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('dividend_yield', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('p_vp', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('valor_mercado', models.DecimalField(blank=True, decimal_places=2, max_digits=24, null=True)),
                ('liquidez', models.DecimalField(blank=True, decimal_places=2, max_digits=24, null=True)),
                ('qtd_imoveis', models.IntegerField(blank=True, null=True)),
                ('preco_m2', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ('aluguel_m2', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ('cap_rate', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('vacancia_media', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'real_estate_fund',
                'indexes': [models.Index(fields=['papel', 'collected_at_utc'], name='idx_ref_papel_collected')],
                'constraints': [models.UniqueConstraint(fields=('run_id', 'papel'), name='uq_real_estate_fund_run_id_papel')],
            },
        ),
        migrations.CreateModel(
            name='RealEstateFundDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_id', models.UUIDField(db_index=True)),
                ('source', models.CharField(max_length=120)),
                ('url', models.URLField(max_length=500)),
                ('detalhe_url', models.URLField(blank=True, max_length=500, null=True)),
                ('collected_at_utc', models.DateTimeField(db_index=True)),
                ('status_coleta', models.CharField(blank=True, max_length=32, null=True)),
                ('identificacao_nome', models.TextField(blank=True, null=True)),
                ('identificacao_segmento', models.CharField(blank=True, max_length=120, null=True)),
                ('identificacao_mandato', models.CharField(blank=True, max_length=120, null=True)),
                ('identificacao_gestao', models.CharField(blank=True, max_length=120, null=True)),
                ('mercado_cotacao', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ('mercado_data_ult_cot', models.CharField(blank=True, max_length=32, null=True)),
                ('mercado_min_52_sem', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ('mercado_max_52_sem', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ('mercado_vol_medio_2m', models.DecimalField(blank=True, decimal_places=2, max_digits=24, null=True)),
                ('mercado_valor_mercado', models.DecimalField(blank=True, decimal_places=2, max_digits=24, null=True)),
                ('mercado_numero_cotas', models.DecimalField(blank=True, decimal_places=2, max_digits=24, null=True)),
                ('mercado_data_relatorio', models.CharField(blank=True, max_length=32, null=True)),
                ('mercado_ult_info_trimestral', models.CharField(blank=True, max_length=32, null=True)),
                ('indicadores_ffo_yield', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('indicadores_ffo_cota', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ('indicadores_dividend_yield', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('indicadores_dividendo_cota', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ('indicadores_p_vp', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('indicadores_vp_cota', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ('resultado_ult_12m_receita', models.DecimalField(blank=True, decimal_places=2, max_digits=24, null=True)),
                ('resultado_ult_3m_receita', models.DecimalField(blank=True, decimal_places=2, max_digits=24, null=True)),
                ('resultado_ult_12m_venda_ativos', models.DecimalField(blank=True, decimal_places=2, max_digits=24, null=True)),
                ('resultado_ult_3m_venda_ativos', models.DecimalField(blank=True, decimal_places=2, max_digits=24, null=True)),
                ('resultado_ult_12m_ffo', models.DecimalField(blank=True, decimal_places=2, max_digits=24, null=True)),
                ('resultado_ult_3m_ffo', models.DecimalField(blank=True, decimal_places=2, max_digits=24, null=True)),
                ('resultado_ult_12m_rend_distribuido', models.DecimalField(blank=True, decimal_places=2, max_digits=24, null=True)),
                ('resultado_ult_3m_rend_distribuido', models.DecimalField(blank=True, decimal_places=2, max_digits=24, null=True)),
                ('balanco_ativos', models.DecimalField(blank=True, decimal_places=2, max_digits=24, null=True)),
                ('balanco_patrimonio_liquido', models.DecimalField(blank=True, decimal_places=2, max_digits=24, null=True)),
                ('imoveis_qtd_imoveis', models.IntegerField(blank=True, null=True)),
                ('imoveis_qtd_unidades', models.IntegerField(blank=True, null=True)),
                ('imoveis_area_m2', models.DecimalField(blank=True, decimal_places=4, max_digits=24, null=True)),
                ('imoveis_preco_m2', models.DecimalField(blank=True, decimal_places=4, max_digits=24, null=True)),
                ('imoveis_aluguel_m2', models.DecimalField(blank=True, decimal_places=4, max_digits=24, null=True)),
                ('imoveis_cap_rate', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('imoveis_vacancia_media', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('imoveis_imoveis_pl_percent', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fund', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='detail', to='api.realestatefund')),
            ],
            options={
                'db_table': 'real_estate_fund_detail',
                'indexes': [models.Index(fields=['run_id', 'status_coleta'], name='idx_ref_detail_run_status')],
            },
        ),
    ]
