# Generated by Codex on 2026-03-21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="realestatefund",
            name="uq_real_estate_fund_run_id_papel",
        ),
        migrations.AlterField(
            model_name="realestatefund",
            name="papel",
            field=models.CharField(db_index=True, max_length=20, unique=True),
        ),
    ]
