# Generated by Codex on 2026-03-21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_fund_upsert_key"),
    ]

    operations = [
        migrations.AlterField(
            model_name="realestatefund",
            name="qtd_imoveis",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="realestatefunddetail",
            name="imoveis_qtd_imoveis",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="realestatefunddetail",
            name="imoveis_qtd_unidades",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
