# Generated by Codex on 2026-05-01

import accounts.models
import accounts.validators
import django.utils.timezone
from django.core.validators import EmailValidator
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                ("last_login", models.DateTimeField(blank=True, null=True, verbose_name="last login")),
                ("email", models.EmailField(max_length=254, unique=True, validators=[EmailValidator(message="Enter a valid email address.")])),
                ("name", models.CharField(max_length=255, validators=[accounts.validators.validate_full_name])),
                ("birth_date", models.DateField(validators=[accounts.validators.validate_birth_date])),
                ("cpf", models.CharField(max_length=11, unique=True, validators=[accounts.validators.validate_cpf])),
                ("is_active", models.BooleanField(default=True)),
                ("is_staff", models.BooleanField(default=False)),
                ("is_authorized", models.BooleanField(default=True)),
                ("date_joined", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "db_table": "account_user",
                "indexes": [
                    models.Index(fields=["email"], name="idx_account_user_email"),
                    models.Index(fields=["cpf"], name="idx_account_user_cpf"),
                    models.Index(fields=["is_active", "is_authorized"], name="idx_account_user_status"),
                ],
            },
            managers=[
                ("objects", accounts.models.UserManager()),
            ],
        ),
    ]
